# Generated by Django 5.1 on 2024-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=40)),
                ('doc', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
