# Generated by Django 5.1 on 2024-10-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_appointment_pn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pn',
            field=models.CharField(default='N/A', max_length=40),
            preserve_default=False,
        ),
    ]
